apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.image.name }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.image.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.image.name }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}
