version: 2.1

parameters:
  dry-run:
    type: boolean
    default: true
  particles-per-cluster:
    type: integer
    default: 5

jobs:
  update-repo:
    docker:
      - image: cimg/base:edge
    # Is this causing checkout to fail? https://app.circleci.com/pipelines/github/olukotun-ts/udacity-k8s/3/workflows/806d08c9-cb4e-4485-8f74-d1c91edab441/jobs/4?invite=true#step-101-73
    # vs. previous commit https://app.circleci.com/pipelines/github/olukotun-ts/udacity-k8s/2/workflows/32d961f9-5044-4b94-a4c6-c5f349ee6367/jobs/2
    # working_directory: particles 
    steps:
      - add_ssh_keys:
          fingerprints: 1b:e6:e3:1e:a2:ce:3d:22:92:88:32:9c:e6:71:ce:57
      - checkout
      - run:
          name: Install yq
          command: |
            wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64.tar.gz -O yq.tar.gz
            tar -xf yq.tar.gz
            sudo mv yq_linux_amd64 /usr/bin/yq
            yq -V
      - run:
          name: Update manifests
          command: |
            export PPC=<<pipeline.parameters.particles-per-cluster>>
            yq --inplace '
              .appVersion = strenv($CIRCLE_BUILD_NUM) |
              .configData.particlesPerCluster = strenv(PPC)' particles/values.yaml

            export VERSION=0.0.$CIRCLE_BUILD_NUM
            yq --inplace '.version = strenv(VERSION)' particles/Chart.yaml
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            helm version
      - run:
          name: Package chart
          command: |
            helm package particles --destination charts
      - run:
          name: Update chart repo index
          command: |
            helm repo index charts --merge charts/index.yaml
      - when:
          condition: <<pipeline.parameters.dry-run>>
          steps:
            - store_artifacts:
                path: particles/values.yaml
            - store_artifacts:
                path: charts
      - unless:
          condition: <<pipeline.parameters.dry-run>>
          steps:
            - run: 
                name: Persist updates
                command: |
                  git config user.email "${CIRCLE_USERNAME}@${CIRCLE_PROJECT_USERNAME}.bot"
                  git config user.name "${CIRCLE_USERNAME}"
                  git commit -am 'Update manifests from CircleCI build $CIRCLE_BUILD_NUM'
                  git push -u origin ghe-pages

workflows:
  version: 2
  default:
    jobs:
      - update-repo
