version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  gcp-gcr: circleci/gcp-gcr@0.15.0

parameters:
  particlesPerCluster:
    type: integer
    default: 5

jobs:
  update-manifests:
    docker:
      - image: cimg/base:edge
    # Is this causing checkout to fail? https://app.circleci.com/pipelines/github/olukotun-ts/udacity-k8s/3/workflows/806d08c9-cb4e-4485-8f74-d1c91edab441/jobs/4?invite=true#step-101-73
    # vs. previous commit https://app.circleci.com/pipelines/github/olukotun-ts/udacity-k8s/2/workflows/32d961f9-5044-4b94-a4c6-c5f349ee6367/jobs/2
    # working_directory: particles 
    steps:
      - checkout
      - run:
          name: Update manifests
          command: |
            # Update configData.particlesPerCluster
            wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64.tar.gz -O yq.tar.gz
            tar -xf yq.tar.gz
            sudo mv yq_linux_amd64

            # command -v yq || wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64.tar.gz -O - | \
            #   tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
            # export PPC=<<pipeline.parameters.particlesPerCluster>>
            # yq --inplace '.configData.particlesPerCluster = strenv(PPC)' particles/values.yaml

            # git config user.email "${CIRCLE_USERNAME}@${CIRCLE_PROJECT_USERNAME}.bot"
            # git config user.name "${CIRCLE_USERNAME}"
            # git commit -am 'Update manifests'
            # git push -u origin ghe-pages
  package-chart:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Package and deliver chart
          command: |
            helm package particles --destination charts

            git config user.email "${CIRCLE_USERNAME}@${CIRCLE_PROJECT_USERNAME}.bot"
            git config user.name "${CIRCLE_USERNAME}"
            git commit -am 'Package chart'
            git push -u origin ghe-pages
  update-index:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Update chart repo index
          command: |
            helm repo index charts --merge charts/index.yaml

            git config user.email "${CIRCLE_USERNAME}@${CIRCLE_PROJECT_USERNAME}.bot"
            git config user.name "${CIRCLE_USERNAME}"
            git commit -am 'Package chart'
            git push -u origin ghe-pages

workflows:
  version: 2
  default:
    jobs:
      - update-manifests
      - package-chart:
          requires:
            - update-manifests
      - update-index:
          requires:
            - package-chart
            