apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod`
  namespace: argocd
spec:
  destination:
    namespace: nginx-prod
    server: https://kubernetes.default.svc
  project: nginx
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/nginx
    repoURL: https://github.com/olukotun-ts/udacity-k8s 
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
      