apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: app-python
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/olukotun-ts/udacity-k8s 
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      prune: true
