appName: particles
appVersion: 1.0.0
namespace: particles-dev
configData:
  valueFile: values.yaml

replicaCount: 3

image:
  name: magneticio/particles
  tag: 1.5.2
  pullPolicy: IfNotPresent
        
service:
  type: LoadBalancer
  port: 15000
  targetPort: 5000

argocd:
  path: particles
  repoURL: https://github.com/olukotun-ts/udacity-k8s
  targetRevision: gke
